# 机器人的配置文件

# 若您的适配器需要Token，请填写此字段
TOKEN: '1ab98aa24bc602323851dbf82fd273af1907c0e39c06c1e04e1907aff4320c05'
# 若您的适配器需要Cookie，请填写此字段
COOKIE: ''
# 若您的适配器需要ws连接，请填写此字段
WSBASE: 'ws://localhost:5500/v1/events'
# 若您的适配器需要请求http地址，请填写此字段
HTTPBASE: 'http://localhost:5500/v1/'

# 所用的适配器
adapters_you_can_choose: ['console']
ADAPTER: 'satori'

# 机器人指令头
PREFIX: '#'

# 用户权限配置
# 格式为 {'user_id': 权限等级}
# 推荐使用：
#   0：guest
#   2：admin
#   3：owner
PERMISSION: {
  '3435578673': 3,
  '2538523045': 3
}